export { default as Homepage } from "./Home/HomePage";
export { default as Aboutpage } from "./About/Aboutpage";
export { default as Privacypage } from "./Privacy/Privacypage";
export { default as Termspage } from "./Terms/Termspage";
export { default as Loginpage } from "./Login/Loginpage";
export { default as Registerpage } from "./Register/Registerpage";
export { default as Forgotpage } from "./Forgot/Forgotpage";
export { default as ContactPage } from "./Contact/Contactpage";
export { default as SetNewPasswordPage } from "./SetPassword/SetPasswordpage";
